// [EXPORT] //
module.exports = [
	{
		cat_id: 'general',
		title: 'General Discussion',
		description: 'General discussions about anything relating to blockchain',
		image: null,
		recentPost: {},
		totalPosts: null,
	},
	{
		cat_id: 'news',
		title: 'News',
		description: 'Latest news about the industry',
		image: null,
		recentPost: {},
		totalPosts: null,
	},
	{
		cat_id: 'ideas',
		title: 'Dapp Ideas, Tips, Tricks',
		description: 'Share some ideas & find new partners!',
		image: null,
		recentPost: {},
		totalPosts: null,
	},
	{
		cat_id: 'smart-contracts',
		title: 'Smart Contracts',
		description: 'Discuss smart contracts, share your smart contracts!',
		image: null,
		recentPost: {},
		totalPosts: null,
	},
	{
		cat_id: 'help',
		title: 'Get Help',
		description: 'Need help? Ask us & we might be able to help with that!',
		image: null,
		recentPost: {},
		totalPosts: null,
	},
	{
		cat_id: 'learn',
		title: 'Learn',
		description: 'Learn about blockchain & learn what it can do for you..',
		image: null,
		recentPost: {},
		totalPosts: null,
	},
	{
		cat_id: 'misc',
		title: 'Misc.',
		description: 'Anything uncategorized',
		image: null,
		recentPost: {},
		totalPosts: null,
	},
]