// [EXPORT] //
module.exports = [
	{
		cat_id: 'general',
		title: 'General Discussion',
		description: 'General discussions about anything relating to blockchain',
		index: 0,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
	{
		cat_id: 'news',
		title: 'News',
		description: 'Latest news about the industry',
		index: 1,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
	{
		cat_id: 'ideas',
		title: 'Dapp Ideas, Tips, Tricks',
		description: 'Share some ideas & find new partners!',
		index: 2,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
	{
		cat_id: 'smart-contracts',
		title: 'Smart Contracts',
		description: 'Discuss smart contracts, share your smart contracts!',
		index: 3,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
	{
		cat_id: 'help',
		title: 'Get Help',
		description: 'Need help? Ask us & we might be able to help with that!',
		index: 4,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
	{
		cat_id: 'learn',
		title: 'Learn',
		description: 'Learn about blockchain & learn what it can do for you..',
		index: 5,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
	{
		cat_id: 'prices',
		title: 'Prices',
		description: 'Discuss prices here',
		index: 6,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
	{
		cat_id: 'misc',
		title: 'Misc.',
		description: 'Anything uncategorized',
		index: 7,
		image: null,
		recentPost: null,
		totalPosts: null,
	},
]