// [EXPORT] //
module.exports = [
	// [VARIANT] //
	// Wing Flavor //
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Plain',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Pineapple BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Honey BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Honey Garlic',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Asian Sesame',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'General Tso',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Mojita Lime',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Buffalo Dry Rub',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Buffalo Mild',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Teriyaki Sauce',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Lousiana Sauce',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Korean BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Ragin\' Cajun',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Mango Habanero',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'flavor',
		name: 'Knockout',
		description: '',
		image: '',
		cost: 0.00,
	},

	// Wing Type //
	{
		cat: 'variant',
		type: 'wing-type',
		name: 'Traditional',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'wing-type',
		name: 'Boneless',
		description: '',
		image: '',
		cost: 0.00,
	},

	// Slider Sauce //
	{
		cat: 'variant',
		type: 'sauce',
		name: 'Spicy Mayo',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'sauce',
		name: 'Chipotle Mayo',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'sauce',
		name: 'Teriyaki Aoli',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'sauce',
		name: 'Thousand Island',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'variant',
		type: 'sauce',
		name: 'BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},

	// [ADDITION] //
	// Slider Appetizer //
	{
		cat: 'addition',
		type: 'slider-appetizer',
		name: 'Fried Mac and Cheese Bites',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'addition',
		type: 'slider-appetizer',
		name: 'Fried Cauliflower Pops',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'addition',
		type: 'slider-appetizer',
		name: 'Fried Pickles',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'addition',
		type: 'slider-appetizer',
		name: 'Mozzerella Sticks',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		cat: 'addition',
		type: 'slider-appetizer',
		name: 'Onion Rings',
		description: '',
		image: '',
		cost: 0.00,
	},

	// [EXTRAS] //
	// Toppings //
	{
		cat: 'extra',
		type: 'topping',
		name: 'Extra Patty',
		description: '',
		image: '',
		cost: 1.00,
	},
	{
		cat: 'extra',
		type: 'topping',
		name: 'Sauteed Onions',
		description: '',
		image: '',
		cost: 0.50,
	},
	{
		cat: 'extra',
		type: 'topping',
		name: 'Jalapenos',
		description: '',
		image: '',
		cost: 0.50,
	},
	{
		cat: 'extra',
		type: 'topping',
		name: 'Mushrooms',
		description: '',
		image: '',
		cost: 0.50,
	},
	{
		cat: 'extra',
		type: 'topping',
		name: 'Beef Bacon',
		description: '',
		image: '',
		cost: 1.75,
	},
	{
		cat: 'extra',
		type: 'topping',
		name: 'Bacon Jam',
		description: '',
		image: '',
		cost: 1.75,
	},
	{
		cat: 'extra',
		type: 'topping',
		name: 'Avacado',
		description: '',
		image: '',
		cost: 1.75,
	},
	{
		cat: 'extra',
		type: 'topping',
		name: 'Crispy Fried Onions',
		description: '',
		image: '',
		cost: 0.75,
	},
]